### ISSUE TITLE
warning: express-sse + gzip compression middleware = no go

### ISSUE THREAD

**Issue by sp00x** [dpskvn/express-sse#17]
Not sure why, but it appears that if you enable the `compression` middleware for gzip support, then sometimes EventSource will just fail silently in Chrome.. just sits there, no events..

Seems to happen with other SSE modules also (e.g. `sse-express`), so not sure how to address it, or what the problem is.

I found out this the hard way spending an hour or so wondering why nothing was coming through, after using  `app.use(new compression())`. Had to selectively use the compression middleware on the routes I wanted  it on instead, avoiding it on the SSE ones.

Might be worth mentioning in the readme to save people some time? :)

**Comment by dpskvn** [comment]
I'd like to fix this, rather than just letting people know about the issue in the readme.

Would you be willing to help out by testing this? I don't have the time to set up a testing environment and it sounds like you have one already. Try the [compression branch](https://github.com/dpskvn/express-sse/tree/compression) and set `isCompressed` in the options to `true`. Let me know how that works out.

Thanks!

**Comment by sp00x** [comment]
Sure, I can try to reproduce it again - I will see if I get time sometime this week!

**Comment by sp00x** [comment]
Ugh, sorry. Will try to squeeze some time in this week.

**Comment by dpskvn** [comment]
Most likely fixed in e156385a4fe9589f8ed4781b154cc30f6dcef434

To be reopened if not.

**Comment by drew-wallace** [comment]
Using the new `isCompressed` option, I'm seeing the connection terminated and reinitialized after every event is being sent.
