### ISSUE TITLE
Initial events are sent to all clients when somebody connects

### ISSUE THREAD

**Issue by Bo98** [dpskvn/express-sse#21]
To reproduce:

```js
const app = express();
const sse = new SSE(["test"]);
app.get('/', sse.init);
app.listen(9000);
```

and then in two terminals: `curl http://localhost:9000`

Observe how the client you connected first receives the initial event twice - one when it connected itself and another when the second client connected:

```
id: 0
data: "test"

id: 1
data: "test"
```

**Comment by maixuanhan** [comment]
In my opinion, there is no such thing as 'initial' event in SSE. Only either `onopen` or `onmessage` or `onerror`. Initial message is actually an `onmessage` event that emitted globally by server side for the whole subscribers. Yes, this kind of initial event concept is totally useless unless you want to notify all the subscribers about new connection. For connection-based initial event, a simple `res.write()` action is good enough.

**Comment by dpskvn** [comment]
When I started working on this library, I didn't really set out to write an SSE library, there were a few out there. I needed something that matched my specific use-case in an application I was working on. This behavior was intentional.

When that piece of code turned into a library, I kept it as is. At this point, I'm hesitant to change the behavior of any part of the library as it's being used in a number of projects, and I simply don't have the time to analyze how they're using it and whether any major changes would impact their code base.

For this reason alone, I'm going to close this issue, but I'll keep it in mind for a re-visit at a later time.
